version: '3'
services:
  db:
    image: 'mysql:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=39750Dm*
      - MYSQL_DATABASE=doodletaskdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=39750Dm*
    ports:
      - '3307:3306'
  app:
    image: damlamutlu/doodle-docker
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/doodletaskdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true'
    depends_on:
      - db